on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install git+https://github.com/laminlabs/laminci
      - run: uv pip install --system git+https://github.com/laminlabs/lamindb
      - run: lamin init
      - run: python scripts/define_types_and_features.py
